name: Docker Build and Push

on:
  push:
    branches:
      - dev-build
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
        build-args: |
          CI_PROJECT_TITLE=${{ github.repository }}
          CI_PROJECT_URL=${{ github.event.repository.html_url }}
          CI_JOB_STARTED_AT=${{ github.event.workflow_run.created_at }}
          CI_COMMIT_SHA=${{ github.sha }}
          CI_COMMIT_REF_NAME=${{ github.ref_name }}
        labels: |
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.created=${{ github.event.workflow_run.created_at }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.ref_name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Move Docker cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Tag and push on tags
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
        docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
